title: "Learning Terraform with Infrastructure as Code in ORACLE CLOUD INFRASTRUCTURE"
description: "Terraform configuration, to create a VCN, Subnet and a Compute Instance"
schemaVersion: 1.1.0
version: "0.0.1"
locale: "en"

variableGroups:
  - title: 'Hidden Variables'
    visible: false
    variables:
      - region
  - title: 'Global variables'
    visible: true
    variables:
      - compartment_id
  - title: 'VCN Variables'
    visible: true
    variables:
      - cidr_block
      - display_name
      # - dns_label
  - title: 'Subnet Variables'
    visible: true
    variables:
      - subnet_cidr_block
      - display_name_subnet
  - title: 'Compute Instance Variables'
    visible: true
    variables:
      - instance_availability_domain
      - instance_shape
      - image_id
      - instance_shape_config_ocpus
      - instance_shape_config_memory_in_gbs
      - num_instances 
      - ssh_public_key


variables:
  region:
    type: oci:identity:region:name
    required: true
    title: "Region"
    description: "Region where the resources will be created"
  
  compartment_id:
    type: oci:identity:compartment:id
    required: true
    title: "Compartment"
    description: "The compartment in which to create compute instance(s) and ATP."

  cidr_block:
    type: string
    required: true
    title: "CIDR Block"
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    description: "The CIDR block of the VCN. A valid CIDR block value."

  display_name:
    type: string
    required: true
    title: "Display Name"
    description: "A user-friendly name for the VCN. Does not have to be unique, and it's changeable."

  # dns_label:
  #   type: string
  #   required: true
  #   title: "DNS Label"
  #   description: "A DNS label for the VCN, used in conjunction with the VNIC's hostname and subnet's DNS label to form a fully qualified domain name (FQDN) for each VNIC within this subnet (for example, bminstance-1.subnet123.vcn1.oraclevcn.com). Not required to be unique, but it's a best practice to set unique DNS labels for VCNs in your tenancy. Must be an alphanumeric string that begins with a letter. The value cannot be changed."

  subnet_cidr_block:
    type: string
    required: true
    title: "Subnet CIDR Block"
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    description: "The CIDR block of the subnet. A valid CIDR block value."

  display_name_subnet:
    type: string
    required: true
    title: "Display Name"
    description: "A user-friendly name for the subnet. Does not have to be unique, and it's changeable."

  instance_shape:
    type: oci:core:instanceshape:name
    required: true
    title: "Instance Shape"
    default: VM.Standard2.1
    dependsOn:
      region: region
      compartmentId: compartment_id

  image_id:
    type: oci:core:image:id
    title: "Image"
    description: "The image used to launch the instance."
    required: true
    dependsOn:
      region: region
      compartmentId: compartment_id

  instance_availability_domain:
    type: oci:identity:availabilitydomain:name
    title: "Availability Domain"
    description: "The availability domain of the instance."
    required: true
    dependsOn:
      region: region
      compartmentId: compartment_id
    default: 1
  
  instance_shape_config_ocpus:
    type: number
    title: "OCPUs"
    description: "The number of OCPUs available to the instance."
    required: true
    default: 1

  instance_shape_config_memory_in_gbs:
    type: number
    title: "Memory in GBs"
    description: "The amount of memory available to the instance, in gigabytes."
    required: true
    default: 2

  num_instances:
    type: number
    title: "Number of Instances"
    description: "The number of instances to launch."
    required: true
    default: 1
  
  ssh_public_key:
    type: oci:core:ssh:publickey
    title: "SSH Public Key"
    description: "The public key portion of the key pair you want to use for SSH access to the instance."
    required: false